### ISSUE TITLE
Improve perceived responsiveness of the bot

### ISSUE THREAD

**Issue by ShaunBaker** [nearform/slack-knowledgebase-chatgpt-responder#238]
Presently, responses can be slow or be perceived to be slow.

We can improve this, by allowing the bot to acknowledge messages it has received whilst working out an answer, as well as being more interactive to make the user aware the bot is working on providing an answer to the question.

**Comment by simoneb** [comment]
Yeah even for the existing "text" feature, considering that the bot takes some time to reply and can't "live type" the answer (due to slack limitations) it would be good to react on the message, e.g. with a thumbs up.

In addition to that, exclusively for voice messages, replying to the user's voice message (e.g. in a thread) with the transcription of the received message, would be useful as well to show what the bot understood from the voice message
